[package]
name = "rust_nes"
version = "0.1.0"
edition = "2021"
description = "A NES Emulator written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
